name: flutter_privacy_screen
description: A flutter plugin that blurs / blacks the screen in the task manager.
version: 1.3.0
homepage: https://github.com/jeroentrappers/flutter_privacy_screen

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.10.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: be.appmire.flutter_privacy_screen
        pluginClass: FlutterPrivacyScreenPlugin
      ios:
        pluginClass: FlutterPrivacyScreenPlugin

